### ISSUE TITLE
python segment_main.py --mode='test' --dcrf=0

### ISSUE THREAD

**Issue by Aa456789** [SketchyScene/SketchyScene#13]
![image](https://user-images.githubusercontent.com/32674957/51373391-1b817480-1b3b-11e9-9088-118145f3af28.png)

Changing FLAGS.ignore_class_bg to true will still report the same error on the next line   
nSketchClasses = FLAGS.nSketchClasses - 1
What is going on here?

**Comment by MarkMoHR** [comment]
Hi @Aa456789 ,

It seems that you are using python2.7, which I suppose leads to the problems.  It is recommended to use python3.5 and TensorFlow1.4.0.

Alternatively, if you still want to run the code under python2.7, you can try to replace all the `FLAGS.xxx` to the values in `configs.py`. For example, you can replace `FLAGS.ignore_class_bg` to `True` or `False` directly as you like. But this is not coding-friendly and might take some time :)
